const sampleBooks = [
  { id: "linux-online", title: "Linux 入門電子書", subtitle: "GitHub Pages 上可直接閱讀的 Linux 基礎教學電子書", author: "Happy eBook 編輯部", category: "Linux 入門", type: "web", format: "網站閱讀", cover: "../assets/images/book-linux-online.svg", description: "直接連到線上版本的 Linux 電子書，包含章節教學、操作範例與閱讀設定。", downloadUrl: "", buyUrl: "", readUrl: "https://j945935cy.github.io/ebook2026linux/", featured: true, popular: true, priceLabel: "免費閱讀" },
  { id: "google-play-books-partner", title: "Google Play 圖書合作夥伴中心", subtitle: "Google Play Books 的出版與上架管理入口", author: "Google Play Books", category: "出版平台", type: "web", format: "網站服務", cover: "../assets/images/book-google-play-books.svg", description: "用來管理圖書上架、發佈與出版設定的官方入口頁。", downloadUrl: "", buyUrl: "", readUrl: "https://play.google.com/books/publish/u/0/?hl=zh_TW", featured: false, popular: false, priceLabel: "前往網站" },
  { id: "ebook-blog-reader", title: "ebook", subtitle: "以教學書風格呈現的線上閱讀網站", author: "ebook945", category: "教學應用", type: "web", format: "網站閱讀", cover: "../assets/images/book-ebook-blog.svg", description: "線上教學書網站，適合章節式學習、教材整理與內容閱讀。", downloadUrl: "", buyUrl: "", readUrl: "https://share.google/JaUEuqAnQegK9zX2d", featured: true, popular: true, priceLabel: "免費閱讀" },
  { id: "word-builder-1200", title: "Word Builder 1200", subtitle: "1200 個核心英文單字的互動式網頁版閱讀教材", author: "Happy eBook 編輯部", category: "英語學習", type: "web", format: "網頁版", cover: "../assets/images/book-word-builder-1200.svg", description: "適合在瀏覽器直接閱讀的英文單字書，整理常用字彙並支援長時間閱讀。", downloadUrl: "", buyUrl: "", readUrl: "../word-builder-1200-single-file.html", featured: true, popular: true, priceLabel: "免費閱讀" },
  { id: "linux-starter", title: "從 Windows 開始學 Linux", subtitle: "用 WSL2 建立第一個穩定的 Linux 學習環境", author: "Happy eBook 編輯部", category: "Linux 入門", type: "web", format: "網頁版 / PDF", cover: "../assets/images/book-linux-starter.svg", description: "用最少阻力開始學 Linux，從安裝、指令、工作流程一路到實作。", downloadUrl: "", buyUrl: "", readUrl: "https://j945935cy.github.io/ebook2026linux/", featured: true, popular: true, priceLabel: "免費閱讀" },
  { id: "epub-writing-guide", title: "EPUB 製作實戰手冊", subtitle: "從內容整理到上架格式，一次掌握電子書製作流程", author: "林書晨", category: "出版製作", type: "paid", format: "EPUB / PDF", cover: "../assets/images/book-epub-guide.svg", description: "適合想把文章、教材或課程筆記整理成正式電子書的創作者。", downloadUrl: "", buyUrl: "#buy-epub-writing-guide", readUrl: "", featured: true, popular: false, priceLabel: "付費購買" },
  { id: "web-book-design", title: "網頁版電子書設計筆記", subtitle: "把靜態內容做成舒服好讀的 Web Book", author: "周映青", category: "前端設計", type: "free", format: "PDF / 原始檔", cover: "../assets/images/book-web-design.svg", description: "整理電子書版面、章節導覽、排版系統與閱讀體驗的設計思路。", downloadUrl: "#download-web-book-design", buyUrl: "", readUrl: "", featured: false, popular: true, priceLabel: "免費下載" },
  { id: "teacher-digital-class", title: "教師的數位教材工作流", subtitle: "把講義、投影片與延伸閱讀整理成持續更新的內容平台", author: "陳雅茹", category: "教學應用", type: "paid", format: "PDF / 範本包", cover: "../assets/images/book-teacher-digital.svg", description: "面向教師與教育工作者，從內容拆解到教學平台建置的完整思路。", downloadUrl: "", buyUrl: "#buy-teacher-digital-class", readUrl: "", featured: false, popular: true, priceLabel: "付費購買" }
];
const typeLabel = { free: "免費", paid: "付費", web: "網頁版" };
const loadBooks = async () => { try { const response = await fetch("books.json"); if (!response.ok) throw new Error(`HTTP ${response.status}`); return await response.json(); } catch (error) { console.warn("books.json 載入失敗，改用內建資料：", error); return sampleBooks; } };
const createTags = (book) => [`<span class="tag ${book.type}">${typeLabel[book.type] || book.type}</span>`,`<span class="tag category">${book.category}</span>`].join("");
const primaryAction = (book) => book.type === "free" ? `<a class="button primary" href="${book.downloadUrl || "#"}">下載閱讀</a>` : book.type === "paid" ? `<a class="button primary" href="${book.buyUrl || "#"}">立即購買</a>` : `<a class="button primary" href="${book.readUrl || `book.html?id=${book.id}`}">前往閱讀</a>`;
const createBookCard = (book) => `<article class="book-card"><div class="book-card-media"><img src="${book.cover}" alt="${book.title} 書封"></div><div class="book-card-body"><h3>${book.title}</h3><p class="book-meta">${book.author} ・ ${book.format}</p><div class="tag-row">${createTags(book)}</div><p>${book.description}</p><div class="card-actions">${primaryAction(book)}<a class="card-link" href="book.html?id=${book.id}">更多資訊</a></div></div></article>`;
const renderList = (selector, books) => { const target = document.querySelector(selector); if (target) target.innerHTML = books.map(createBookCard).join(""); };
const initHome = async () => { const books = await loadBooks(); renderList("[data-home-featured]", books.filter((book) => book.featured)); renderList("[data-home-popular]", books.filter((book) => book.popular)); };
const initBooksPage = async () => { const books = await loadBooks(); const grid = document.querySelector("[data-books-grid]"); const typeFilters = [...document.querySelectorAll("[data-type-filter]")]; const categoryFilters = [...document.querySelectorAll("[data-category-filter]")]; if (!grid) return; let activeType = "all"; let activeCategory = "all"; const render = () => { const filtered = books.filter((book) => (activeType === "all" || book.type === activeType) && (activeCategory === "all" || book.category === activeCategory)); grid.innerHTML = filtered.length ? filtered.map(createBookCard).join("") : `<div class="empty-state"><h3>目前沒有符合條件的作品</h3><p>你可以切換篩選條件，或之後再回來看看。</p></div>`; }; typeFilters.forEach((button) => button.addEventListener("click", () => { activeType = button.dataset.typeFilter; typeFilters.forEach((item) => item.classList.toggle("is-active", item === button)); render(); })); categoryFilters.forEach((button) => button.addEventListener("click", () => { activeCategory = button.dataset.categoryFilter; categoryFilters.forEach((item) => item.classList.toggle("is-active", item === button)); render(); })); render(); };
const initBookPage = async () => { const books = await loadBooks(); const id = new URLSearchParams(window.location.search).get("id"); const book = books.find((item) => item.id === id) || books[0]; const target = document.querySelector("[data-book-detail]"); if (!target || !book) return; document.title = `${book.title} | Happy eBook`; target.innerHTML = `<div class="book-cover-panel"><div class="book-cover-stage"><img src="${book.cover}" alt="${book.title} 書封"></div></div><div class="book-content-panel"><div class="tag-row">${createTags(book)}</div><h1>${book.title}</h1><p class="book-summary">${book.subtitle}</p><p>${book.description}</p><div class="meta-list"><div class="meta-item"><span>作者</span><strong>${book.author}</strong></div><div class="meta-item"><span>分類</span><strong>${book.category}</strong></div><div class="meta-item"><span>格式</span><strong>${book.format}</strong></div><div class="meta-item"><span>取得方式</span><strong>${book.priceLabel}</strong></div></div><div class="cta-row">${primaryAction(book)}<a class="button secondary" href="books.html">返回列表</a></div></div>`; };
const initNav = () => { const nav = document.querySelector("[data-site-nav]"); const toggle = document.querySelector("[data-nav-toggle]"); toggle?.addEventListener("click", () => nav?.classList.toggle("is-open")); };
const boot = () => { initNav(); const page = document.body.dataset.page; if (page === "home") initHome(); if (page === "books") initBooksPage(); if (page === "book") initBookPage(); };
boot();

